// Code generated by "stringer -type ErrCode -linecomment -output errcode_string.go"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-200]
	_ = x[ErrCodeUnauthorized-401]
	_ = x[ErrCodeNotFound-404]
	_ = x[Error-1000]
	_ = x[ParamsError-1001]
}

const (
	_ErrCode_name_0 = "success"
	_ErrCode_name_1 = "unauthorized"
	_ErrCode_name_2 = "not found"
	_ErrCode_name_3 = "errorparams error"
)

var (
	_ErrCode_index_3 = [...]uint8{0, 5, 17}
)

func (i ErrCode) String() string {
	switch {
	case i == 200:
		return _ErrCode_name_0
	case i == 401:
		return _ErrCode_name_1
	case i == 404:
		return _ErrCode_name_2
	case 1000 <= i && i <= 1001:
		i -= 1000
		return _ErrCode_name_3[_ErrCode_index_3[i]:_ErrCode_index_3[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
